# Generated by Django 4.1.3 on 2022-11-11 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_storage_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='storage',
            field=models.ForeignKey(choices=[('lost', 'Потерял'), ('find', 'Нашел')], on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.storage'),
        ),
    ]
