# Generated by Django 4.1.3 on 2022-11-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
