# Generated by Django 4.1.3 on 2022-11-14 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0014_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegrams', to='post.storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('whatsapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapps', to='post.storage')),
            ],
        ),
    ]
