# Generated by Django 4.1.3 on 2022-11-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_contact_telegram_alter_contact_whatsapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
