# Generated by Django 4.1.3 on 2022-11-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storage',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
