# Generated by Django 4.1.3 on 2022-11-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_storage_telegram_storage_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='telegram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='storage',
            name='whatsapp',
            field=models.CharField(max_length=13),
        ),
    ]
